//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmWeb.Web.Scheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GmWeb.Web.Scheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d:\iCalendar\basic.ics.
        /// </summary>
        internal static string iCalLocalFile {
            get {
                return ResourceManager.GetString("iCalLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN:VCALENDAR
        ///PRODID:-//Google Inc//Google Calendar 70.9054//EN
        ///VERSION:2.0
        ///CALSCALE:GREGORIAN
        ///METHOD:PUBLISH
        ///X-WR-CALNAME:ECML PKDD 2015
        ///X-WR-TIMEZONE:Europe/Lisbon
        ///X-WR-CALDESC:The European Conference on Machine Learning and Principles and
        ///  Practice of\nKnowledge Discovery in Databases (ECMLPKDD) will take place i
        /// n Porto\,\nPortugal\, from September 7th to 11th\, 2015 (http://www.ecmlpkd
        /// d2015.org).\n\nThis event is the leading European scientific event on machi
        /// ne learning and\ndata mining and bui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iCalTestData {
            get {
                return ResourceManager.GetString("iCalTestData", resourceCulture);
            }
        }
    }
}
