//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmWeb.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GmWeb.Logic.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [ID] AS AgencyID, [Name] AS AgencyName FROM tblAgency WHERE [ID] = {0}.
        /// </summary>
        public static string AgencyPartnerSQL {
            get {
                return ResourceManager.GetString("AgencyPartnerSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.ClientID
        ///FROM   tblClient c
        ///INNER JOIN tblClientCategory cc ON c.ClientID = cc.ClientID
        ///INNER JOIN tblClientCategoryDate ccd ON cc.ClientCategoryID = ccd.ClientCategoryID
        ///WHERE  cc.ClientCategoryID = {0}
        ///AND    cc.DateCreated IS NOT NULL
        ///AND    ccd.Assigned = 1
        ///AND    ccd.Attended = 1.
        /// </summary>
        public static string AttendedServiceSQL {
            get {
                return ResourceManager.GetString("AttendedServiceSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8gATj9U7qn.
        /// </summary>
        public static string AuthorizeNetLogonID {
            get {
                return ResourceManager.GetString("AuthorizeNetLogonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27H4fv4hRw5C.
        /// </summary>
        public static string AuthorizeNetLogonIDSandbox {
            get {
                return ResourceManager.GetString("AuthorizeNetLogonIDSandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3fQ9R98g6mwUES2g.
        /// </summary>
        public static string AuthorizeNetTransactionKey {
            get {
                return ResourceManager.GetString("AuthorizeNetTransactionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7J58bu2Mp6HFa44c.
        /// </summary>
        public static string AuthorizeNetTransactionKeySandbox {
            get {
                return ResourceManager.GetString("AuthorizeNetTransactionKeySandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency: {0}&lt;br&gt;
        ///Program: {1}&lt;br&gt;
        ///Project ID: {2}&lt;br&gt;
        ///Description: {3}&lt;br&gt;
        ///&lt;br&gt;
        ///Please be advised that service to 7c2 for contracts associated with Project ID {2} has been temporarily interrupted due to the contract revision process.&lt;br&gt;
        ///&lt;br&gt;
        ///We apologize for the inconvenience. If you have any questions, please contact your grant coordinator, {4} at {5}.&lt;br&gt;
        ///&lt;br&gt;
        ///Thank you..
        /// </summary>
        public static string ContractRevisionMessage {
            get {
                return ResourceManager.GetString("ContractRevisionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision for Contracts associated with Project ID {0}.
        /// </summary>
        public static string ContractRevisionSubject {
            get {
                return ResourceManager.GetString("ContractRevisionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1}:&lt;br /&gt;
        ///&lt;br /&gt;
        ///A {2} for {6:c} has been submitted against your checking account by us at {3}. Please click &lt;a href=&apos;{4}&apos;&gt;here&lt;/a&gt; to approve or to reject this {2}. If we receive no response after {5} days, this {2} will expire.&lt;br /&gt;
        ///&lt;br /&gt;
        ///Thank you,&lt;br /&gt;
        ///{3}.
        /// </summary>
        public static string DonorECheckApprovalMessage {
            get {
                return ResourceManager.GetString("DonorECheckApprovalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An electronic check request has been submitted.
        /// </summary>
        public static string DonorECheckApprovalSubject {
            get {
                return ResourceManager.GetString("DonorECheckApprovalSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string DonorECheckTimeoutDays {
            get {
                return ResourceManager.GetString("DonorECheckTimeoutDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following donation has been made to {0}:&lt;br /&gt;
        ///&lt;br /&gt;
        ///Donor: {1}&lt;br /&gt;
        ///&lt;br /&gt;
        ///Amount: {2:c}&lt;br /&gt;
        ///Type of donation: {3}&lt;br /&gt;
        ///Date: {4:MMMM d, yyyy, h:mm tt}&lt;br /&gt;
        ///&lt;br /&gt;
        ///Phone: {5}&lt;br /&gt;
        ///Email: {6}&lt;br /&gt;
        ///&lt;br /&gt;
        ///Pledge amount: {7:c}&lt;br /&gt;
        ///In Honor Of: {8}&lt;br /&gt;
        ///&lt;br /&gt;
        ///Thank you,&lt;br /&gt;
        ///GoodMojo, Inc (GoodMojo.Us).
        /// </summary>
        public static string DonorEmail {
            get {
                return ResourceManager.GetString("DonorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following donation has been made to {0}:&lt;br /&gt;
        ///&lt;br /&gt;
        ///Donor: {1}&lt;br /&gt;
        ///&lt;br /&gt;
        ///Number of items: {2}&lt;br /&gt;
        ///Total value: {3:c}&lt;br /&gt;
        ///Type of transaction:  {4}&lt;br /&gt;
        ///Date: {5:MMMM d, yyyy, h:mm tt}&lt;br /&gt;
        ///&lt;br /&gt;
        ///Phone: {6}&lt;br /&gt;
        ///Email: {7}&lt;br /&gt;
        ///&lt;br /&gt;
        ///Thank you,&lt;br /&gt;
        ///GoodMojo, Inc (GoodMojo.Us).
        /// </summary>
        public static string DonorEmailInKind {
            get {
                return ResourceManager.GetString("DonorEmailInKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation receipt.
        /// </summary>
        public static string DonorEmailSubject {
            get {
                return ResourceManager.GetString("DonorEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [ID] AS AgencyID, [Name] AS AgencyName FROM tblAgency WHERE FedTaxID = &apos;{0}&apos;.
        /// </summary>
        public static string FedTaxIDPartnerSQL {
            get {
                return ResourceManager.GetString("FedTaxIDPartnerSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT AgencyDocumentationID AS DocumentID,
        ///       DocumentPath AS Filename,
        ///       CONVERT(varchar, UploadedDate, 101) AS UploadedDate,
        ///       UploadedByUserID AS UploadedBy,
        ///       CASE
        ///           WHEN UploadedBy = &apos;{0}&apos; THEN &apos;images/unlock.png&apos;
        ///           ELSE &apos;images/lock.png&apos;
        ///       END AS Status
        ///FROM tblAgencyDocumentation
        ///WHERE DocumentTypeID IN ({1})
        ///AND AgencyID = &apos;{2}&apos;
        ///AND Deleted = 0
        ///AND RIGHT(DocumentPath, 4) = &apos;.pdf&apos;
        ///ORDER BY DocumentPath.
        /// </summary>
        public static string GetAgencyDocumentation {
            get {
                return ResourceManager.GetString("GetAgencyDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT pmt.PaymentKey,
        ///       a.Name AS [AGENCY NAME],
        ///       rcp.ContractID AS [CONTRACT ID],
        ///       pmt.PaymentSubmittedDate AS [REPORTING PERIOD],
        ///       pmt.PaymentKey AS [TRANSACTION ID],
        ///       CASE
        ///           WHEN ISNULL(pmt.StaffApproved, 0) = 1 THEN &apos;X&apos;
        ///           ELSE &apos;&apos;
        ///       END AS [GC],
        ///       CASE
        ///           WHEN ISNULL(pmt.ManagerApproved, 0) = 1 THEN &apos;X&apos;
        ///           ELSE &apos;&apos;
        ///       END AS [MGR]
        ///FROM   tblPayments pmt
        ///INNER JOIN tblRelCtrPrj rcp ON pmt.ContractID = rcp.ContractID [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetApprovalStatusReversalItems {
            get {
                return ResourceManager.GetString("GetApprovalStatusReversalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT pmt.PaymentKey,
        ///       a.Name AS [AGENCY NAME],
        ///       a.VendorCCSF AS [VENDOR],
        ///       pmt.PaymentKey AS [TRANSACTION ID],
        ///       rcp.GrantDetail AS [GRANT ID],
        ///       pTotal.NetAmount AS [NET AMOUNT]
        ///FROM   tblPayments pmt
        ///INNER JOIN tblRelCtrPrj rcp ON pmt.ContractID = rcp.ContractID
        ///INNER JOIN tblProjects p ON rcp.ProjectID = p.ProjectID
        ///INNER JOIN tblAgency a ON p.AgencyID = a.ID
        ///LEFT OUTER JOIN (
        ///    SELECT pd.PaymentKey, SUM(pd.AmountRequested) AS SubmittedAmount, SUM(pd.NetAmountRe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetInitiatePaymentProcessItems {
            get {
                return ResourceManager.GetString("GetInitiatePaymentProcessItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT c.ClientID, c.Email
        ///FROM tblClient c
        ///INNER JOIN tblDonorTransaction dt ON c.ClientID = dt.ClientID
        ///WHERE dt.DonorTransactionID IN ({0}).
        /// </summary>
        public static string GetTransactionEmails {
            get {
                return ResourceManager.GetString("GetTransactionEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT pt.ProcessTypeID
        ///FROM   tblProcessType pt
        ///INNER JOIN tblProcessStep ps ON pt.ProcessTypeID = ps.ProcessTypeID
        ///WHERE pt.ClientCategoryID = {0}
        ///AND   ps.Checked = 1
        ///AND   ps.DateRecorded IS NULL
        ///AND   pt.ProcessTypeIDlkp = {1}.
        /// </summary>
        public static string IncompleteStepSQL {
            get {
                return ResourceManager.GetString("IncompleteStepSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following donation has been made in your honor to {0}:&lt;br /&gt;
        ///&lt;br /&gt;
        ///Donor: {1}&lt;br /&gt;
        ///&lt;br /&gt;
        ///Amount: {2:c}&lt;br /&gt;
        ///Type of donation: {3}&lt;br /&gt;
        ///Date: {4:MMMM d, yyyy, h:mm tt}&lt;br /&gt;
        ///&lt;br /&gt;
        ///Phone: {5}&lt;br /&gt;
        ///Email: {6}&lt;br /&gt;
        ///&lt;br /&gt;
        ///Pledge amount: {7:c}&lt;br /&gt;
        ///&lt;br /&gt;
        ///Thank you,&lt;br /&gt;
        ///GoodMojo, Inc (GoodMojo.Us).
        /// </summary>
        public static string InHonorEmail {
            get {
                return ResourceManager.GetString("InHonorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pledge has been made in your honor.
        /// </summary>
        public static string InHonorEmailSubject {
            get {
                return ResourceManager.GetString("InHonorEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited to be a partner with Agency {0}. The invitation name is {1}. It&apos;s description is {2}..
        /// </summary>
        public static string InviteeEmailMessage {
            get {
                return ResourceManager.GetString("InviteeEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited.
        /// </summary>
        public static string InviteeEmailSubject {
            get {
                return ResourceManager.GetString("InviteeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string IsLiveApplication {
            get {
                return ResourceManager.GetString("IsLiveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail is being sent from TOTAL GRANT SOLUTION(tm) to notify you that one of the 7c2 submissions from your agency has been NOT APPROVED.
        ///                    &lt;br /&gt;&lt;br /&gt;
        ///The details are as follows:&lt;br /&gt;
        ///Project #{0}&lt;br /&gt;
        ///Contract #{1}&lt;br /&gt;
        ///{2}
        ///&lt;br /&gt;&lt;br /&gt;
        ///Request Month: {3:MMMM, yyyy}
        ///&lt;br /&gt;&lt;br /&gt;
        ///Please contact your Grant Coordinator, {4} {5}, to resolve the issue(s).
        ///&lt;br /&gt;&lt;br /&gt;
        ///You may re-submit your expense info for the affected month as long as future months have not already been s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotApprovedMessage {
            get {
                return ResourceManager.GetString("NotApprovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT TOP 1000 a.[ID] AS AgencyID, a.[Name] AS AgencyName
        ///FROM tblAgency a
        ///LEFT OUTER JOIN tblAgencyBudgetItem abi ON a.ID = abi.AgencyID
        ///LEFT OUTER JOIN (
        ///    SELECT AgencyID, SUM(ItemAmount) AS TotalAmount FROM tblAgencyBudgetItem GROUP BY AgencyID
        ///    ) abit ON a.ID = abit.AgencyID
        ///LEFT OUTER JOIN (
        ///    SELECT AgencyID, COUNT(*) AS BoardCount FROM tblBoardOfDirectors GROUP BY AgencyID
        ///    ) bd ON a.ID = bd.AgencyID
        ///WHERE.
        /// </summary>
        public static string PartnersSQL {
            get {
                return ResourceManager.GetString("PartnersSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT cc.ClientCategoryID
        ///FROM   tblClientCategory cc
        ///INNER JOIN tblClientCategoryDate ccd ON cc.ClientCategoryID = ccd.ClientCategoryID
        ///WHERE  cc.ClientCategoryID = {0}
        ///AND    cc.DateCreated IS NOT NULL
        ///AND    ccd.Assigned = 1.
        /// </summary>
        public static string RegisteredForServiceSQL {
            get {
                return ResourceManager.GetString("RegisteredForServiceSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT cc.ClientCategoryID
        ///FROM   tblClientCategory cc
        ///INNER JOIN tblClientCategoryDate ccd ON cc.ClientCategoryID = ccd.ClientCategoryID
        ///WHERE  cc.ClientCategoryID = {0}
        ///AND    ccd.Attended = 1
        ///AND    ccd.Signature IS NOT NULL.
        /// </summary>
        public static string ServiceSigRequiredSQL {
            get {
                return ResourceManager.GetString("ServiceSigRequiredSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Grant Solutions (TGS) User Agreement Terms and Conditions&lt;br /&gt;
        ///&lt;br /&gt;
        ///IMPORTANT: BY USING TOTAL GRANT SOLUTIONS, YOU ARE AGREEING TO BE BOUND BY THE FOLLOWING TEKMECA SOFTWARE SINGLE USE LICENSE AGREEMENT TERMS AND CONDITIONS:&lt;br /&gt;
        /// &lt;br /&gt;
        ///PLEASE READ THIS SOFTWARE LICENSE AGREEMENT (&quot;LICENSE&quot;) CAREFULLY BEFORE USING OR DOWNLOADING THE SOFTWARE ACCOMPANYING THIS LICENSE. YOU ARE AGREEING TO BE BOUND BY THE TERMS OF THIS LICENSE.  IF YOU DO NOT AGREE TO THE TERMS OF THIS LICENSE, DO NOT USE TGS.&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TGSUserAgreement {
            get {
                return ResourceManager.GetString("TGSUserAgreement", resourceCulture);
            }
        }
    }
}
